language: objective-c
osx_image: xcode9.2

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean test -destination "platform=iOS Simulator,OS=11.2,name=iPhone 8" -workspace SwiftScraper.xcworkspace -scheme SwiftScraper CODE_SIGNING_REQUIRED=NO | xcpretty
